2019-04-05 12:03:57,805 ERROR Exceptions.ISAFExceptions       Error during loading 'Modules/Credentials/FTPbruteforce'

Error: No module named 'Modules.Credentials.FTPbruteforce'

It should be valid path to the module. Use <tab> key multiple times for completion.
Traceback (most recent call last):
  File "/root/PycharmProjects/ISAF/Utils/__init__.py", line 81, in import_exploit
    module = importlib.import_module(path)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'Modules.Credentials.FTPbruteforce'
